#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc rule -a mpv state=floating
bspc rule -a Sxiv state=floating
bspc rule -a Zathura state=tiled

$XDG_CONFIG_HOME/polybar/launch.sh
